; PlatformIO configuration for ESP32 Composite Video Hello World
; https://docs.platformio.org/en/latest/projectconf/index.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=0
